FROM pomomondreganto/forcad_base:latest

########## CUSTOMIZE ##########

RUN apt-get install -y git libssl-dev libffi-dev build-essential

ADD ./checkers/requirements.txt /checker_requirements.txt
RUN pip install -r /checker_requirements.txt

ADD ./checkers /checkers

ENV PWNLIB_NOTERM=true

########## END CUSTOMIZE ##########

ADD backend /app

ADD ./docker_config/celery/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER nobody

CMD ["/entrypoint.sh"]