DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS flags;
DROP TABLE IF EXISTS stolenflags;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS teamtasks;
DROP TABLE IF EXISTS teamtaskslog;
DROP TABLE IF EXISTS globalconfig;

DROP FUNCTION IF EXISTS update_teamtasks_status(INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS calculate(FLOAT, FLOAT, FLOAT, BOOLEAN);
DROP FUNCTION IF EXISTS recalculate_rating(INTEGER, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_first_bloods();