DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS flags CASCADE;
DROP TABLE IF EXISTS stolenflags CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS teamtasks CASCADE;
DROP TABLE IF EXISTS teamtaskslog CASCADE;
DROP TABLE IF EXISTS globalconfig CASCADE;

DROP FUNCTION IF EXISTS update_teamtasks_status(INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS calculate(FLOAT, FLOAT, FLOAT, BOOLEAN);
DROP FUNCTION IF EXISTS recalculate_rating(INTEGER, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_first_bloods();
DROP FUNCTION IF EXISTS fix_teamtasks();