ARG version=latest

FROM ghcr.io/pomo-mondreganto/forcad_base:${version}

COPY backend /app

ENV CONFIG_PATH /app/config.yml
COPY config.yml ${CONFIG_PATH}

COPY ./docker_config/initializer/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
