server {
        listen 80;
        server_name default;
        location / {
                gzip on;
                gzip_static on;
                gzip_types text/plain text/css text/javascript application/javascript;
                gzip_disable "msie6";
                root /var/www/front;
                try_files $uri /index.html;
                autoindex off;
                expires max;
        }
}
