import sys

import click

from cli import utils, models


@click.command(help='Validate config structure')
@click.option(
    '--full',
    is_flag=True,
    help='Check full config (generated by setup command).',
)
def validate(full: bool):
    if full:
        utils.print_bold('Validating full configuration for kubernetes')
        config = utils.load_config()
        check_admin(config.admin)
    else:
        utils.print_bold('Validating basic configuration for kubernetes')
        config = utils.load_basic_config()
        if config.admin:
            check_admin(config.admin)

    utils.print_success('Configuration is valid!')


def check_admin(config: models.AdminConfig):
    if config.username == 'admin':
        utils.print_error(
            '"admin" username is not allowed for YC Postgres cluster. '
            'Please, change admin.username in config and try again.',
        )
        sys.exit(1)

    if len(config.password) < 8:
        utils.print_error(
            'Password must be 8 or more characters long. '
            'Please, change admin.password in config and try again.',
        )
        sys.exit(1)
