FROM pomomondreganto/forcad_base:latest

RUN apt-get install -y socat

ADD backend /app

ADD ./docker_config/socat_flag_submitter/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]